parameters:
#    harvest_cloud_user.example.class: HarvestCloud\UserBundle\Example

services:
#    harvest_cloud_user.example:
#        class: %harvest_cloud_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
